### ISSUE TITLE
IOError: [Errno 21] Is a directory: '/new_image'

### ISSUE THREAD

**Issue by jameh198p** [Supervisor/supervisor#1009]
I installed odoo app (image_upload) at my custom folder on Ubuntu, and I also chmod 777 on folder 'New_image' for this app?But The odoo still returned following error once I import data. Is there anyone help me? Thanks in advance.

Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/james/odoo-addons/import_image/wizard/import_image_wizard.py", line 102, in get_file
    self.write_image(csv_data)
  File "/home/james/odoo-addons/import_image/wizard/import_image_wizard.py", line 78, in write_image
    image_path = urllib.urlretrieve(row.get('image'), os.path.join(os.getcwd(), 'new_image'))[0]
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 21] Is a directory: '/new_image'

**Comment by mnaberez** [comment]
This is the [Supervisor](http://supervisord.org) issue tracker but the error above is from a completely different program.  We can't help with this.
