### ISSUE TITLE
SyntaxError: invalid syntax when run on docker

### ISSUE THREAD

**Issue by iPePPe** [Supervisor/supervisor#1086]
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.0b2.dev0', 'console_scripts', 'supervisord')()
  File "/usr/local/lib/python3.5/dist-packages/supervisor/supervisord.py", line 353, in main
    options.realize(args, doc=__doc__)
  File "/usr/local/lib/python3.5/dist-packages/supervisor/options.py", line 438, in realize
    Options.realize(self, *arg, **kw)
  File "/usr/local/lib/python3.5/dist-packages/supervisor/options.py", line 295, in realize
    self.process_config_file()
  File "/usr/local/lib/python3.5/dist-packages/supervisor/options.py", line 497, in process_config_file
    Options.process_config_file(self, do_usage=do_usage)
  File "/usr/local/lib/python3.5/dist-packages/supervisor/options.py", line 303, in process_config_file
    self.read_config(self.configfile)
  File "/usr/local/lib/python3.5/dist-packages/supervisor/options.py", line 579, in read_config
    section.process_group_configs = self.process_groups_from_parser(parser)
  File "/usr/local/lib/python3.5/dist-packages/supervisor/options.py", line 642, in process_groups_from_parser
    result_handler = self.import_spec(result_handler)
  File "/usr/local/lib/python3.5/dist-packages/supervisor/options.py", line 360, in import_spec
    mod = importlib.import_module(moduleName)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/supervisor_stdout.py", line 22
    print '%s %s | %s'%(headers['processname'], headers['channel'], data),
                     ^
SyntaxError: invalid syntax

**Comment by mnaberez** [comment]
> File "/usr/local/lib/python3.5/dist-packages/supervisor_stdout.py", line 22

This error isn't from Supervisor itself, it's from a plugin.  From the filename in the error message, it might be [this plugin](https://github.com/coderanger/supervisor-stdout) but I'm not sure.  Please report this error on the issue tracker for the plugin you are using.
