### ISSUE TITLE
pkg_resources.DistributionNotFound: meld3>=0.6.5

### ISSUE THREAD

**Issue by 52fhy** [Supervisor/supervisor#1145]
```
# pip install supervisor

You are using pip version 7.1.0, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting supervisor
Requirement already satisfied (use --upgrade to upgrade): meld3>=0.6.5 in /usr/lib/python2.6/site-packages (from supervisor)
Installing collected packages: supervisor
  Running setup.py install for supervisor
Successfully installed supervisor-3.3.4
```

```

# supervisord -v

Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
```

env:

- Linux ac86ca134db2 4.4.111-boot2docker #1 SMP Thu Jan 11 16:25:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- CentOS release 6.8 (Final)
- Python 2.6.6
- pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)

**Comment by mnaberez** [comment]
Please use https://github.com/Supervisor/meld3/issues/23 to discuss this issue.
