### ISSUE TITLE
python 3.8 cgi.escape function removed

### ISSUE THREAD

**Issue by MattBlack85** [Supervisor/supervisor#1257]
In python 3.8 cgi.escape will be removed

```
  File "/usr/local/lib/python3.8/site-packages/supervisor/supervisord.py", line 40, in <module>
    from supervisor.options import ServerOptions
  File "/usr/local/lib/python3.8/site-packages/supervisor/options.py", line 54, in <module>
    from supervisor import xmlrpc
  File "/usr/local/lib/python3.8/site-packages/supervisor/xmlrpc.py", line 24, in <module>
    from supervisor.http import NOT_DONE_YET
  File "/usr/local/lib/python3.8/site-packages/supervisor/http.py", line 24, in <module>
    from supervisor.medusa import default_handler
  File "/usr/local/lib/python3.8/site-packages/supervisor/medusa/default_handler.py", line 20, in <module>
    from supervisor.medusa.util import html_repr
  File "/usr/local/lib/python3.8/site-packages/supervisor/medusa/util.py", line 1, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/usr/local/lib/python3.8/cgi.py)
```

https://docs.python.org/3.8/library/cgi.html

**Comment by Euthal02** [comment]
issue still exists on my env.
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mka/Documents/web2py/gluon/__init__.py", line 37, in <module>
    from .globals import current
  File "/home/mka/Documents/web2py/gluon/globals.py", line 24, in <module>
    from gluon.serializers import json, custom_json
  File "/home/mka/Documents/web2py/gluon/serializers.py", line 10, in <module>
    from gluon.languages import lazyT
  File "/home/mka/Documents/web2py/gluon/languages.py", line 19, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.8/cgi.py)
```
```
Name: supervisor
Version: 4.1.0
Summary: A system for controlling process state under UNIX
Home-page: http://supervisord.org/
Author: Chris McDonough
Author-email: chrism@plope.com
License: BSD-derived (http://www.repoze.org/LICENSE.txt)
Location: /home/mka/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
```
