### ISSUE TITLE
Memmon: socket.error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Matvik** [Supervisor/supervisor#1261]
Memmon in unable to start, repeated error in memmon-stderr---supervisor-IgIsou.log:

> Checking programs yii-queue-worker=1073741824
Traceback (most recent call last):
  File "/usr/local/bin/memmon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/superlance/memmon.py", line 418, in main
    memmon.runforever()
  File "/usr/local/lib/python2.7/dist-packages/superlance/memmon.py", line 152, in runforever
    infos = self.rpc.supervisor.getAllProcessInfo()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 509, in request
    self.connection.request('POST', handler, request_body, self.headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 530, in connect
    self.sock.connect(self.socketfile)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied

Supervisor version 3.3.1, Debian 9.

**Comment by mnaberez** [comment]
> File "/usr/local/lib/python2.7/dist-packages/superlance/memmon.py", line 418, in main

This is the issue tracker for the Supervisor package, but the issue above seems to be about the Superlance package.  Please reported this issue in to the [Superlance](https://github.com/supervisor/superlance) repository.
