### ISSUE TITLE
supervisorctl takes too long to execute command

### ISSUE THREAD

**Issue by gilles** [Supervisor/supervisor#131]
[root@ip-10-245-174-225] ~ $ supervisorctl stop XXX
^CTraceback (most recent call last):
  File "/usr/local/bin/supervisorctl", line 9, in <module>
    load_entry_point('supervisor==3.0a12', 'console_scripts', 'supervisorctl')()
  File "/usr/local/lib/python2.6/dist-packages/supervisor/supervisorctl.py", line 1114, in main
    c.onecmd(" ".join(options.args))
  File "/usr/local/lib/python2.6/dist-packages/supervisor/supervisorctl.py", line 144, in onecmd
    return do_func(arg)
  File "/usr/local/lib/python2.6/dist-packages/supervisor/supervisorctl.py", line 732, in do_stop
    result = supervisor.stopProcess(name)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.6/dist-packages/supervisor/xmlrpc.py", line 463, in request
    r = self.connection.getresponse()
  File "/usr/lib/python2.6/httplib.py", line 990, in getresponse
    response.begin()
  File "/usr/lib/python2.6/httplib.py", line 391, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.6/httplib.py", line 349, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.6/socket.py", line 427, in readline
    data = recv(1)
KeyboardInterrupt

supervisorctl status show 'STOPPED' and the process does not exists.
The log file shows:
2012-06-19 14:31:08,722 INFO stopped: XXX (terminated by SIGTERM)

I can turn on more debugging if you need

**Comment by mnaberez** [comment]
The changes for this issue (c5d5cad04ad30fa451d077a529c1f65dae657246, d948fc5170e9cd348470ede63a2382adba29f0fd, 11ffa5115649f80235e2864754bb603b106d7053, 53663093ecedeada3b15aec13058d21482aa2ee9) were released in [Supervisor 3.2.0](https://github.com/Supervisor/supervisor/blob/3.2.0/CHANGES.txt#L7-L9).

**Comment by hnrindani** [comment]
Seems like this is a never ending bug. I came across this recently and seems like nothing is working for me. Does anybody have the experience of working with Upstart?

**Comment by chrysls** [comment]
I noticed the issue only when you call it with "service".

`sudo service supervisor restart myproject` - Takes ages to execute
`sudo supervisorctl restart myproject - Almost instant

**Comment by verseal** [comment]
Stop all your jobs, and the start one by one. You'll find which job causes problem
