### ISSUE TITLE
Crash on Supervisord Startup

### ISSUE THREAD

**Issue by weissi** [Supervisor/supervisor#145]
Everytime I start supervisord (both, version 3.0a8-1 from Ubuntu and 3.0a12 from easy_install) crashes with this error while starting up (`supervisord -n`)

```
2012-08-28 13:00:17,487 INFO spawned: 'umi27.root.public' with pid 20799
2012-08-28 13:00:17,489 INFO spawned: 'localhost.alle.neaXXX' with pid 20800 
2012-08-28 13:00:17,492 INFO spawned: 'localhost.alle.karlsXXX' with pid 20801
2012-08-28 13:00:17,509 INFO spawned: 'localhost.root.public' with pid 20802
2012-08-28 13:00:17,511 INFO spawned: 'localhost.alle.badenbadenkst' with pid 20803
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.0a8', 'console_scripts', 'supervisord')()
  File "/usr/lib/pymodules/python2.6/supervisor/supervisord.py", line 371, in main
    go(options)
  File "/usr/lib/pymodules/python2.6/supervisor/supervisord.py", line 381, in go
    d.main()
  File "/usr/lib/pymodules/python2.6/supervisor/supervisord.py", line 94, in main
    self.run()
  File "/usr/lib/pymodules/python2.6/supervisor/supervisord.py", line 111, in run
    self.runforever()
  File "/usr/lib/pymodules/python2.6/supervisor/supervisord.py", line 263, in runforever
    [ group.transition() for group  in pgroups ]
  File "/usr/lib/pymodules/python2.6/supervisor/process.py", line 680, in transition
    proc.transition()
  File "/usr/lib/pymodules/python2.6/supervisor/process.py", line 518, in transition
    self.spawn()
  File "/usr/lib/pymodules/python2.6/supervisor/process.py", line 226, in spawn
    self.dispatchers, self.pipes = self.config.make_dispatchers(self)
  File "/usr/lib/pymodules/python2.6/supervisor/options.py", line 1560, in make_dispatchers
    stdout_fd,stderr_fd,stdin_fd = p['stdout'],p['stderr'],p['stdin']
TypeError: 'NoneType' object is unsubscriptable
```

Supervisor controls ~350 processes and the crash is always when trying `[program:localhost.alle.badenbadenkst]`. The config entry for localhost.alle.badenbadenkst ist

```
[program:localhost.alle.badenbadenkst]
command=python /home/uroot/fcvs/apps/thales/pyreplica/pyreplica.py -s "badenbadenkst" -i "localhost.alle.badenbadenkst" "host=umi21 dbname=badenbadenkst user=postgres" "host=localhost dbname=alle user=postgres"
autorestart=unexpected
exitcodes=0
user=uroot
redirect_stderr=true
startretries=50
```

**Comment by mnaberez** [comment]
> This is "fixed" in master. At least supervisor no longer crashes if it can't spawn a process due to a greater number of file descriptors being opened than is permitted by the environment.

The fix quoted above is commit ffcc311f3634f7df1144c5325f8e77e69f57971f.
