### ISSUE TITLE
Supervisor do not detect python and micropython app crash

### ISSUE THREAD

**Issue by lodygaw** [Supervisor/supervisor#1492]
Hi!
I want to configure Supervisor for keeping two apps running on my Raspberry Pi project. One of them is UI written in micropython and the other one is data handler written in python3. 
This is my configuration:
```
[group:display]
programs=ui,data_handler

[program:ui]
directory=/home/pi/display
command=/home/pi/lv_micropython/ports/unix/micropython /home/pi/display/main.py
autostart=true
autorestart=true
stderr_logfile=/var/log/ui.err.log
stdout_logfile=/var/log/ui.out.log
priority=501

[program:data_handler]
directory=/home/pi/display
command=python3 /home/pi/display/data_handler.py
autorestart=true
autostart=true
stderr_logfile=/var/log/data_handler.err.log
stdout_logfile=/var/log/data_handler.out.log
priority=500
```

For testing I have created some scenarios in which the micropython and python apps would artificially raise an exceptions.
The problem is that I can see that the program crashed, I can see exceptions in logs, but supervisorctl still shows apps as `RUNNING` and do not restart them. 

 /var/log/data_handler.err.log:
```
...

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/display/socket_server.py", line 48, in send_recv
    raise Exception("Test Supervisord")
Exception: Test Supervisord
```

 /var/log/ui.out.log:
```
...

Traceback (most recent call last):
  File "/home/pi/display/panels/main_panel.py", line 165, in <lambda>
  File "/home/pi/display/functions.py", line 47, in get_panel
  File "/home/pi/display/panels/battery_panel.py", line 11, in __init__
Exception: Test Supervisord
```

I have noticed that the stack trace of micropython app goes to `stdout` so there can be an issue with how micropython handles the errors, but python app also does not restart when crashed so I assume that it is more possible that I don't understand something here. 
Any help appreciated!

**Comment by lodygaw** [comment]
I think that I resolved the issue myself. The problem is that both my python and micropython apps have child threads and in both cases exceptions were raised there. As exceptions were not "propagating" to the main thread the apps remain running.
