### ISSUE TITLE
supervisord start failed：AttributeError: 'module' object has no attribute 'asyncore_25'

### ISSUE THREAD

**Issue by ChenJhua** [Supervisor/supervisor#1496]
python: 2.7
supervisord: 4.2.4

use default config
```
echo_supervisord_conf > /etc/supervisord.conf
```
start supervisord
```
~ /home/share/Python-2.7/lib/supervisor # python /home/share/Python-2.7/lib/supervisor/supervisord.py -c /etc/supervisord.conf 
Traceback (most recent call last):
  File "/home/share/Python-2.7/lib/supervisor/supervisord.py", line 38, in <module>
    from supervisor.medusa import asyncore_25 as asyncore
  File "/home/share/Python-2.7/lib/supervisor/medusa/asyncore_25.py", line 58, in <module>
    from supervisor.compat import as_string, as_bytes
  File "/home/share/Python-2.7/lib/supervisor/compat.py", line 114, in <module>
    from xmlrpc.client import Fault
  File "/home/share/Python-2.7/lib/supervisor/xmlrpc.py", line 20, in <module>
    from supervisor.medusa.http_server import get_header
  File "/home/share/Python-2.7/lib/supervisor/medusa/http_server.py", line 18, in <module>
    import supervisor.medusa.asyncore_25 as asyncore
AttributeError: 'module' object has no attribute 'asyncore_25'
```
When I swap http_server.py lines 18 and 19，no errors
```
~ /home/share/Python-2.7/lib/supervisor # python /home/share/Python-2.7/lib/supervisor/supervisord.py -c /etc/supervisord.conf 
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
For help, use /home/share/Python-2.7/lib/supervisor/supervisord.py -h
```
coding
```
~ /home/share/Python-2.7/lib/supervisor # cat /home/share/Python-2.7/lib/supervisor/medusa/http_server.py | head -n 20
# -*- Mode: Python -*-
#
#       Author: Sam Rushing <rushing@nightmare.com>
#       Copyright 1996-2000 by Sam Rushing
#                                                All Rights Reserved.
#
RCS_ID =  '$Id: http_server.py,v 1.12 2004/04/21 15:11:44 akuchling Exp $'

# python modules
import re
import socket
import sys
import time

from supervisor.compat import as_bytes

# async modules
18: import supervisor.medusa.asyncore_25 as asyncore
19: import supervisor.medusa.asynchat_25 as asynchat

```

**Comment by mnaberez** [comment]
> ```
> # python /home/share/Python-2.7/lib/supervisor/supervisord.py -c /etc/supervisord.conf
> ```

`supervisord` is not intended to run be this way.  It's intended to be [installed](http://supervisord.org/installing.html) as a package with `pip install supervisor` or downloaded and installed with `python setup.py install`.  It is then run with the command `supervisord` (which is a [`console_script`](https://github.com/Supervisor/supervisor/blob/4.2.4/setup.py#L93-L97) installed by setuptools).  

If the normal installation process is not done, or the commands are not run the intended way, the results will be unpredictable.  Since `supervisord` is still [tested on CI](https://github.com/Supervisor/supervisor/actions) on 2.7 and doesn't have weird import errors, I'm going to close this issue.

**Comment by ChenJhua** [comment]
> I don't agree with you, I use pip install

i use pypi download whl install
```
~ /data/cjh # python -m pip install supervisor-4.2.4-py2.py3-none-any.whl 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing ./supervisor-4.2.4-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from supervisor==4.2.4) (42.0.2)
Installing collected packages: supervisor
Successfully installed supervisor-4.2.4
WARNING: You are using pip version 20.1.1; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
~ /data/cjh # python /usr/lib/
binfmt.d/                   games/                      jvm/                        libestr.so.0.0.0            libgpg-error.so.0.22.0      polkit-1/                   tmpfiles.d/
.build-id/                  gcc/                        jvm-commmon/                libfastjson.so              liblogging-stdlog.so        python2.7/                  tuned/
cpp                         grub/                       jvm-exports/                libfastjson.so.4            liblogging-stdlog.so.0      rpm/                        udev/
crda/                       java/                       jvm-private/                libfastjson.so.4.2.0        liblogging-stdlog.so.0.0.0  rsyslog/                    yum-plugins/
debug/                      java-1.5.0/                 kbd/                        libgcrypt.so                locale/                     sendmail                    
dracut/                     java-1.6.0/                 kdump/                      libgcrypt.so.20             modprobe.d/                 sendmail.postfix            
firewalld/                  java-1.7.0/                 kernel/                     libgcrypt.so.20.2.2         modules/                    sse2/                       
firmware/                   java-1.8.0/                 libestr.so                  libgpg-error.so             modules-load.d/             sysctl.d/                   
fontconfig/                 java-ext/                   libestr.so.0                libgpg-error.so.0           NetworkManager/             systemd/                    
~ /data/cjh # python /usr/lib/python2.7/site-packages/supervisor/supervisord.py -c /etc/supervisord.conf 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 38, in <module>
    from supervisor.medusa import asyncore_25 as asyncore
  File "/usr/lib/python2.7/site-packages/supervisor/medusa/asyncore_25.py", line 58, in <module>
    from supervisor.compat import as_string, as_bytes
  File "/usr/lib/python2.7/site-packages/supervisor/compat.py", line 114, in <module>
    from xmlrpc.client import Fault
  File "/usr/lib/python2.7/site-packages/supervisor/xmlrpc.py", line 20, in <module>
    from supervisor.medusa.http_server import get_header
  File "/usr/lib/python2.7/site-packages/supervisor/medusa/http_server.py", line 18, in <module>
    import supervisor.medusa.asyncore_25 as asyncore
AttributeError: 'module' object has no attribute 'asyncore_25'
```

**Comment by mnaberez** [comment]
```
~ /data/cjh # python /usr/lib/python2.7/site-packages/supervisor/supervisord.py -c /etc/supervisord.conf 
```

`supervisord` is not intended to run be this way.  It is intended to be run with the command `supervisord` (which is a [console_script](https://github.com/Supervisor/supervisor/blob/4.2.4/setup.py#L93-L97) installed by setuptools).  If the commands are not run the intended way, the results will be unpredictable.

**Comment by ChenJhua** [comment]
> Thanks for your answer, I tried to unzip the source and use python setup.py install. After the installation is successful, there will be an error

```
~ /data/cjh/supervisor-4.2.4 # python /usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg/supervisor/supervisord.py -c /etc/supervisord.conf 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg/supervisor/supervisord.py", line 38, in <module>
    from supervisor.medusa import asyncore_25 as asyncore
  File "/usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg/supervisor/medusa/asyncore_25.py", line 58, in <module>
    from supervisor.compat import as_string, as_bytes
  File "/usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg/supervisor/compat.py", line 114, in <module>
    from xmlrpc.client import Fault
  File "/usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg/supervisor/xmlrpc.py", line 20, in <module>
    from supervisor.medusa.http_server import get_header
  File "/usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg/supervisor/medusa/http_server.py", line 18, in <module>
    import supervisor.medusa.asyncore_25 as asyncore
AttributeError: 'module' object has no attribute 'asyncore_25'

```

```
SIS3.0.60.0 /data/cjh/supervisor-4.2.4 # python setup.py install
running install
running bdist_egg
running egg_info
creating supervisor.egg-info
writing requirements to supervisor.egg-info/requires.txt
writing supervisor.egg-info/PKG-INFO
writing top-level names to supervisor.egg-info/top_level.txt
writing dependency_links to supervisor.egg-info/dependency_links.txt
writing entry points to supervisor.egg-info/entry_points.txt
writing manifest file 'supervisor.egg-info/SOURCES.txt'
reading manifest file 'supervisor.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'docs/.build'
writing manifest file 'supervisor.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/supervisor
copying supervisor/compat.py -> build/lib/supervisor
copying supervisor/rpcinterface.py -> build/lib/supervisor
copying supervisor/dispatchers.py -> build/lib/supervisor
copying supervisor/loggers.py -> build/lib/supervisor
copying supervisor/events.py -> build/lib/supervisor
copying supervisor/poller.py -> build/lib/supervisor
copying supervisor/confecho.py -> build/lib/supervisor
copying supervisor/socket_manager.py -> build/lib/supervisor
copying supervisor/web.py -> build/lib/supervisor
copying supervisor/options.py -> build/lib/supervisor
copying supervisor/process.py -> build/lib/supervisor
copying supervisor/supervisord.py -> build/lib/supervisor
copying supervisor/datatypes.py -> build/lib/supervisor
copying supervisor/childutils.py -> build/lib/supervisor
copying supervisor/states.py -> build/lib/supervisor
copying supervisor/xmlrpc.py -> build/lib/supervisor
copying supervisor/http.py -> build/lib/supervisor
copying supervisor/pidproxy.py -> build/lib/supervisor
copying supervisor/templating.py -> build/lib/supervisor
copying supervisor/supervisorctl.py -> build/lib/supervisor
copying supervisor/__init__.py -> build/lib/supervisor
copying supervisor/http_client.py -> build/lib/supervisor
creating build/lib/supervisor/tests
copying supervisor/tests/test_process.py -> build/lib/supervisor/tests
copying supervisor/tests/test_confecho.py -> build/lib/supervisor/tests
copying supervisor/tests/test_xmlrpc.py -> build/lib/supervisor/tests
copying supervisor/tests/test_poller.py -> build/lib/supervisor/tests
copying supervisor/tests/base.py -> build/lib/supervisor/tests
copying supervisor/tests/test_socket_manager.py -> build/lib/supervisor/tests
copying supervisor/tests/test_dispatchers.py -> build/lib/supervisor/tests
copying supervisor/tests/test_http.py -> build/lib/supervisor/tests
copying supervisor/tests/test_loggers.py -> build/lib/supervisor/tests
copying supervisor/tests/test_states.py -> build/lib/supervisor/tests
copying supervisor/tests/test_end_to_end.py -> build/lib/supervisor/tests
copying supervisor/tests/test_supervisord.py -> build/lib/supervisor/tests
copying supervisor/tests/test_templating.py -> build/lib/supervisor/tests
copying supervisor/tests/test_datatypes.py -> build/lib/supervisor/tests
copying supervisor/tests/test_http_client.py -> build/lib/supervisor/tests
copying supervisor/tests/test_web.py -> build/lib/supervisor/tests
copying supervisor/tests/test_events.py -> build/lib/supervisor/tests
copying supervisor/tests/test_childutils.py -> build/lib/supervisor/tests
copying supervisor/tests/test_rpcinterfaces.py -> build/lib/supervisor/tests
copying supervisor/tests/test_supervisorctl.py -> build/lib/supervisor/tests
copying supervisor/tests/test_pidproxy.py -> build/lib/supervisor/tests
copying supervisor/tests/test_options.py -> build/lib/supervisor/tests
copying supervisor/tests/__init__.py -> build/lib/supervisor/tests
creating build/lib/supervisor/medusa
copying supervisor/medusa/logger.py -> build/lib/supervisor/medusa
copying supervisor/medusa/producers.py -> build/lib/supervisor/medusa
copying supervisor/medusa/util.py -> build/lib/supervisor/medus
......
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/asyncore_25.py to asyncore_25.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/auth_handler.py to auth_handler.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/xmlrpc_handler.py to xmlrpc_handler.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/default_handler.py to default_handler.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/counter.py to counter.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/filesys.py to filesys.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/http_server.py to http_server.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/medusa/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/supervisor/http_client.py to http_client.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying supervisor.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying supervisor.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying supervisor.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying supervisor.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying supervisor.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying supervisor.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying supervisor.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/supervisor-4.2.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing supervisor-4.2.4-py2.7.egg
creating /usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg
Extracting supervisor-4.2.4-py2.7.egg to /usr/lib/python2.7/site-packages
Adding supervisor 4.2.4 to easy-install.pth file
Installing echo_supervisord_conf script to /usr/bin
Installing pidproxy script to /usr/bin
Installing supervisorctl script to /usr/bin
Installing supervisord script to /usr/bin

Installed /usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg
Processing dependencies for supervisor==4.2.4
Searching for setuptools==44.1.1
Best match: setuptools 44.1.1
Adding setuptools 44.1.1 to easy-install.pth file
Installing easy_install script to /usr/bin
Installing easy_install-3.8 script to /usr/bin

Using /usr/lib/python2.7/site-packages
Finished processing dependencies for supervisor==4.2.4
```

**Comment by ChenJhua** [comment]
> python /usr/lib/python2.7/site-packages/supervisor-4.2.4-py2.7.egg/supervisor/supervisord.py -c /etc/supervisord.conf

Excuse me, I used `supervisord -c /etc/sueprvisord.conf` to start successfully, I always thought it was the same as the old version, sorry for the inconvenience
