### ISSUE TITLE
Internal Server Error seen on 3.0b1

### ISSUE THREAD

**Issue by gregkmoff** [Supervisor/supervisor#213]
I see the following when I attempt to run a supervisorctl command:

error: <class 'xmlrpclib.ProtocolError'>, <ProtocolError for 127.0.0.1/RPC2: 500 Internal Server Error>: file: /usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py line: 471

From supervisord.log:

2054-12-01 12:46:30,926 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,939 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,947 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,955 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,962 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,968 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,974 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,980 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,986 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,992 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:30,998 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2054-12-01 12:46:31,004 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

2013-02-05 20:16:44,900 CRIT Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 373, in continue_request
    body = xmlrpc_marshal(value)
  File "/usr/lib64/python2.6/site-packages/supervisor/xmlrpc.py", line 157, in xmlrpc_marshal
    body = xmlrpclib.dumps(value,  methodresponse=ismethodresponse)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1132, in dumps
    data = m.dumps(params)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 677, in dumps
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 759, in dump_array
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 780, in dump_struct
    dump(v, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 699, in __dump
    f(self, value, write)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 710, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits

**Comment by rmstar** [comment]
I hit this as well, but don't know how to reproduce it. Looks like a 64-bit int is getting passed to xmlrpclib, which raises an exception because xmlrpc doesn't support 64-bit values.
As a workaround, can we convert the value to a string before before passing it to xmlrpclib.dumps()?

**Comment by mnaberez** [comment]
> I hit this as well, but don't know how to reproduce it. I saw it when I did supervisorctl status.

What version of Supervisor are you using?

> As a workaround, can we convert the value to a string before before passing it to xmlrpclib.dumps()?

Probably not, that would be a breaking change for existing consumers of the XML-RPC API.

**Comment by rmstar** [comment]
I'm using version 3.0b2.

**Comment by mnaberez** [comment]
Looking at the [log above](https://github.com/Supervisor/supervisor/issues/213#issue-10665756):

    2054-12-01 12:46:30,939 CRIT Traceback (most recent call last):
    ...
    2054-12-01 12:46:30,947 CRIT Traceback (most recent call last):
    ...
    2054-12-01 12:46:30,955 CRIT Traceback (most recent call last):
    ...

The year 2054 is far in the future.  [rpcinterface.py](https://github.com/Supervisor/supervisor/blob/3.2.0/supervisor/rpcinterface.py#L598-L600) converts the datetime to a Unix timestamp integer.  This is likely the source of the error.

    $ python
    Python 2.7.11 (default, Dec  5 2015, 14:44:53)
    >>> import datetime, time, xmlrpclib
    >>> d = datetime.date(2054, 12, 01)
    >>> i = int(time.mktime(d.timetuple()))
    >>> i
    2679724800
    >>> xmlrpclib.MAXINT
    2147483647L
    >>> i > xmlrpclib.MAXINT
    True
    >>> xmlrpclib.dumps((i,))
    Traceback (most recent call last):
    ...
    OverflowError: int exceeds XML-RPC limits

@rmstar Can you please check the main Supervisor log file and let me know if you find a date far into the future?

**Comment by rmstar** [comment]
@mnaberez I don't see timestamps  far into the future.

**Comment by mnaberez** [comment]
> I don't see timestamps far into the future.

What operating system are you using?

**Comment by rmstar** [comment]
I'm using Ubuntu 14.04

**Comment by mnaberez** [comment]
> I'm using Ubuntu 14.04

You can see the maximum PID value with `cat /proc/sys/kernel/pid_max` but I believe on Linux the maximum is `4*1024*1024 = 4194304`.  That's well within `xmlrpclib.MAXINT = 2147483647L`.  I don't think it's the PID.  

I don't see any candidates for large integers in `supervisor.getAllProcessInfo()` other than timestamps.  I'd expect you should be be able to find a far future timestamp in your log, but it may have rotated or been deleted.  The original error was [likely](https://github.com/Supervisor/supervisor/issues/213#issuecomment-180512582) caused by timestamps.

**Comment by rmstar** [comment]
Thank @mnaberez. pid_max on my system is 131072. I'll check if I can locate any unexpected timestamps in the rotated logs.
