### ISSUE TITLE
Supervisor crash: Too many open files ( > 1024)

### ISSUE THREAD

**Issue by pavelsmolka** [Supervisor/supervisor#489]
I am maintaining around 200 processes with supervisord. For each of them, supervisord opens an 'out' log file, 'err' log file and couple of pipes. If the total limit of open file handlers exceeds 1024, supervisor crashes.

I run `supervisord -n` to see the errors. When the processes spawn, the first error occuring is as follows:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 66, in more
  File "/usr/local/lib/python2.7/dist-packages/supervisor/rpcinterface.py", line 282, in startit
  File "/usr/local/lib/python2.7/dist-packages/supervisor/process.py", line 219, in spawn
  File "/usr/local/lib/python2.7/dist-packages/supervisor/options.py", line 1690, in make_dispatchers
    dispatchers[stdout_fd] = POutputDispatcher(proc, etype, stdout_fd)
  File "/usr/local/lib/python2.7/dist-packages/supervisor/dispatchers.py", line 98, in __init__
  File "/usr/local/lib/python2.7/dist-packages/supervisor/options.py", line 452, in getLogger
    backups, stdout)
  File "/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py", line 346, in getLogger
  File "/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py", line 172, in __init__
  File "/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
IOError: [Errno 24] Too many open files: '/var/log/supervisor/program_my_process.log'
```

This occurs around 3 times, but supervisor still seems to carry on. Around 2 seconds later, it crashes. The last error before the crash is similar to the above:

```
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 9, in <module>
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 366, in main
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 376, in go
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 83, in main
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 100, in run
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 254, in runforever
  File "/usr/local/lib/python2.7/dist-packages/supervisor/process.py", line 706, in transition
  File "/usr/local/lib/python2.7/dist-packages/supervisor/process.py", line 555, in transition
  File "/usr/local/lib/python2.7/dist-packages/supervisor/process.py", line 219, in spawn
  File "/usr/local/lib/python2.7/dist-packages/supervisor/options.py", line 1690, in make_dispatchers
  File "/usr/local/lib/python2.7/dist-packages/supervisor/dispatchers.py", line 98, in __init__
  File "/usr/local/lib/python2.7/dist-packages/supervisor/options.py", line 452, in getLogger
  File "/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py", line 346, in getLogger
  File "/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py", line 172, in __init__
  File "/usr/local/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
IOError: [Errno 24] Too many open files: '/var/log/supervisor/program_another_process.log'
```

I don't mind if the processes fail to start, but supervisor crashing (and leaving all its processes running unmaintained) is kind of a big deal.

**Comment by razvanphp** [comment]
So this is 2 years old and it's still not released? We just got into this limit too...

**Comment by zhangcheng** [comment]
@razvanphp I can say at least the latest version 3.3.0 has this bug fixed.

**Comment by Suvitruf** [comment]
3.3.1 still has this issue.
