### ISSUE TITLE
ImportError: No module named pwd on windows 7

### ISSUE THREAD

**Issue by eromoe** [Supervisor/supervisor#493]
I follow the doc
`echo_supervisord_conf > supervisord.conf`
`supervisord -c supervisord.conf`

but error occurs:

```
E:\supervisor>supervisord -c supervisord.conf
Traceback (most recent call last):
  File "E:\Python27\Scripts\supervisord-script.py", line 9, in <module>
    load_entry_point('supervisor==3.1.2', 'console_scripts', 'supervisord')()
  File "build\bdist.win32\egg\pkg_resources.py", line 351, in load_entry_point
  File "build\bdist.win32\egg\pkg_resources.py", line 2363, in load_entry_point
  File "build\bdist.win32\egg\pkg_resources.py", line 2088, in load
  File "E:\Python27\lib\site-packages\supervisor\supervisord.py", line 41, in <module>
    from supervisor.options import ServerOptions
  File "E:\Python27\lib\site-packages\supervisor\options.py", line 11, in <module>
    import pwd
ImportError: No module named pwd
```

Then I try to install `pwd`, but

```
E:\supervisor>pip install pwd
Downloading/unpacking pwd
  Could not find any downloads that satisfy the requirement pwd
Cleaning up...
No distributions at all found for pwd
Storing debug log for failure in C:\Users\yyx\pip\pip.log
```

**Comment by Jimilian** [comment]
What need to do (to code) to run Supervisor on Windows? Can you explain in 2-3 phrases why it's impossible now?

**Comment by alexsilva** [comment]
https://github.com/alexsilva/supervisor.git

I have the need to work with 'supervisor' both Linux and Windows, so as not found solution for Windows, created a fork and started working on it.
At least the part of management processes are working, but things related to Linux I had to remove.

**Comment by initialneil** [comment]
I used `cygwin` to run `supervisor` and it works.
