### ISSUE TITLE
python manage.py runserver failed 

### ISSUE THREAD

**Issue by likesxuqiang** [Supervisor/supervisor#537]
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/django/core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/djsupervisor/management/commands/supervisor.py", line 163, in run_from_argv
    return super(Command,self).run_from_argv(argv)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/djsupervisor/management/commands/supervisor.py", line 175, in handle
    return supervisord.main(("-c",cfg_file))
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/supervisor-4.0.0_dev-py3.4.egg/supervisor/supervisord.py", line 346, in main
    options.realize(args, doc=**doc**)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/supervisor-4.0.0_dev-py3.4.egg/supervisor/options.py", line 471, in realize
    Options.realize(self, _arg, *_kw)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/supervisor-4.0.0_dev-py3.4.egg/supervisor/options.py", line 318, in realize
    self.process_config()
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/supervisor-4.0.0_dev-py3.4.egg/supervisor/options.py", line 531, in process_config
    Options.process_config(self, do_usage=do_usage)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/supervisor-4.0.0_dev-py3.4.egg/supervisor/options.py", line 326, in process_config
    self.process_config_file(do_usage)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/supervisor-4.0.0_dev-py3.4.egg/supervisor/options.py", line 357, in process_config_file
    self.read_config(self.configfile)
  File "/home/ubuntu/autolib/venv/lib/python3.4/site-packages/supervisor-4.0.0_dev-py3.4.egg/supervisor/options.py", line 558, in read_config
    parser.read_file(fp)
  File "/usr/lib/python3.4/configparser.py", line 691, in read_file
    self._read(f, source)
  File "/usr/lib/python3.4/configparser.py", line 993, in _read
    for lineno, line in enumerate(fp, start=1):
TypeError: 'OnDemandStringIO' object is not iterable

**Comment by sindhujit1** [comment]
Any update on this ? I am facing similar issue.
