### ISSUE TITLE
HTTP 500 error trying to read logs on web server

### ISSUE THREAD

**Issue by jpblair** [Supervisor/supervisor#627]
When trying to click a process name to see its logs, I get a generic 500 error.  Here's the log printout with log level set to BLATHER:

2015-06-29 10:11:38	response = self.callback()
2015-06-29 10:11:38	raise RPCError(getattr(Faults, why))
2015-06-29 10:11:38	File "/usr/lib/python2.7/dist-packages/supervisor/web.py", line 165, in __call__
2015-06-29 10:11:38	File "/usr/lib/python2.7/dist-packages/supervisor/web.py", line 46, in more
2015-06-29 10:11:38	body = self.render()
2015-06-29 10:11:38	File "/usr/lib/python2.7/dist-packages/supervisor/web.py", line 197, in render
2015-06-29 10:11:38	File "/usr/lib/python2.7/dist-packages/supervisor/rpcinterface.py&quot;, line 577, in readProcessStdoutLog
2015-06-29 10:11:38	RPCError
2015-06-29 10:11:38	2015-06-29 14:11:38,512 TRAC Web interface error:Traceback (most recent call last):
2015-06-29 10:11:38	tail = rpcinterface.readProcessLog(processname, -1024, 0)
2015-06-29 10:11:38	return self._readProcessLog(name, offset, length, 'stdout')
2015-06-29 10:11:38	File "/usr/lib/python2.7/dist-packages/supervisor/rpcinterface.py&quot;, line 566, in _readProcessLog
2015-06-29 10:11:38	2015-06-29 14:11:38,512 TRAC 10.128.133.188:56588 - - [29/Jun/2015:14:11:38 +0000] "GET /tail.html?processname=webskedconsumer%3A00 HTTP/1.1" 500 288
2015-06-29 10:11:38	2015-06-29 14:11:38,510 BLAT read event caused by <socket._socketobject object at 0x7ff3e9069a60>
2015-06-29 10:11:38	2015-06-29 14:11:38,510 BLAT read event caused by <socket._socketobject object at 0x7ff3e83a5360>

**Comment by mnaberez** [comment]
What version of Supervisor are you using?

**Comment by jpblair** [comment]
3.0, which I see isn't the latest.  I'm installing using the command `pip install supervisor-stdout==0.1.1`.  Should I be doing this differently to get the latest version?

**Comment by jpblair** [comment]
@mnaberez What do I need to do to get this fix?  Do I need to wait until a new release version?

**Comment by mnaberez** [comment]
I fixed it on master and [3.2-branch](https://github.com/Supervisor/supervisor/tree/3.2-branch).  It will be included in the next release (3.2.0).
