### ISSUE TITLE
IOError: [Errno 21] Is a directory: '/home/<username>/' when starting supervisor

### ISSUE THREAD

**Issue by dvreed77** [Supervisor/supervisor#637]
I am getting errors trying to start supervisord.  I think its probably a conflict between my kernel python and Anaconda that I have installed in my home directory.  Here is the traceback

```
<username>@carbon:~> sudo /usr/bin/supervisord -n -c /etc/supervisord.conf
2015-07-20 12:28:42,480 CRIT Supervisor running as root (no user in config file)
2015-07-20 12:28:42,481 WARN Included extra file "/etc/supervisord.d/kibana.conf" during parsing
2015-07-20 12:28:42,497 INFO RPC interface 'supervisor' initialized
2015-07-20 12:28:42,497 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-07-20 12:28:42,497 INFO supervisord started with pid 19609
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.1.3', 'console_scripts', 'supervisord')()
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/supervisord.py", line 366, in main
    go(options)
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/supervisord.py", line 376, in go
    d.main()
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/supervisord.py", line 83, in main
    self.run()
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/supervisord.py", line 100, in run
    self.runforever()
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/supervisord.py", line 254, in runforever
    [ group.transition() for group  in pgroups ]
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/process.py", line 706, in transition
    proc.transition()
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/process.py", line 550, in transition
    self.spawn()
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/process.py", line 219, in spawn
    self.dispatchers, self.pipes = self.config.make_dispatchers(self)
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/options.py", line 1690, in make_dispatchers
    dispatchers[stdout_fd] = POutputDispatcher(proc, etype, stdout_fd)
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/dispatchers.py", line 98, in __init__
    backups=backups)
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/options.py", line 452, in getLogger
    backups, stdout)
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/loggers.py", line 346, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/home/<username>/anaconda/lib/python2.7/site-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 21] Is a directory: '/home/<username>/'
<username>@carbon:~> which supervisord
~/anaconda/bin/supervisord
```

**Comment by mnaberez** [comment]
The traceback indicates that Supervisor is trying to create a log file for a subprocess but the filename it was given is a directory, not a file.  You probably have a line similar to this in your config file:

    [program:x]
    stdout_logfile=/home/username/     ;should a file like: /home/username/log.txt

Unfortunately, this causes `supervisord` to crash.  The crash was already reported in #87 and fixed in fd22ca8 and 4ede6d4.  The fix will be released in Supervisor 3.2.
