### ISSUE TITLE
Error when running supervisord

### ISSUE THREAD

**Issue by josemanimala** [Supervisor/supervisor#644]
(epsilon)root@localhost:/# supervisord -c $epsilon/conf/supervisord.conf
Traceback (most recent call last):
  File "/root/.virtualenvs/epsilon/bin/supervisord", line 11, in <module>
    sys.exit(main())
  File "/root/.virtualenvs/epsilon/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 366, in main
    go(options)
  File "/root/.virtualenvs/epsilon/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 376, in go
    d.main()
  File "/root/.virtualenvs/epsilon/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 83, in main
    self.run()
  File "/root/.virtualenvs/epsilon/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 91, in run
    self.add_process_group(config)
  File "/root/.virtualenvs/epsilon/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 125, in add_process_group
    events.notify(events.ProcessGroupAddedEvent(name))
AttributeError: 'module' object has no attribute 'ProcessGroupAddedEvent'

I get this error when running supervisor on the commandline. The above function was removed from the events.py.

Version:3.1.3

**Comment by mnaberez** [comment]
> AttributeError: 'module' object has no attribute 'ProcessGroupAddedEvent'
>
> I get this error when running supervisor on the commandline. The above function was removed from the events.py.

It's definitely present in the [3.1.3 source](https://github.com/Supervisor/supervisor/blob/3.1.3/supervisor/events.py#L160).  I tried to reproduce your error on a clean installation using the steps below but I wasn't able to see it.  You may have a broken installation or a modified version of Supervisor.  I'm going to close this issue for now but if you can give us a way to reproduce it similar to the steps below, we can reopen.

    $ virtualenv --no-site-packages venv27
    New python executable in venv27/bin/python2.7
    Also creating executable in venv27/bin/python
    Installing setuptools, pip...done.
    $ cd venv27/

    venv27$ bin/python --version
    Python 2.7.10
    
    venv27$ bin/pip install supervisor==3.1.3
    Downloading/unpacking supervisor==3.1.3
      Downloading supervisor-3.1.3.tar.gz (391kB): 391kB downloaded
      Running setup.py (path:/path/to/venv27/build/supervisor/setup.py) egg_info for package supervisor
      ...
    Successfully installed supervisor meld3
    Cleaning up...
    
    venv27$ bin/supervisord --version
    3.1.3
    
    venv27$ vim supervisord.conf
    venv27$ cat supervisord.conf
    [supervisord]
    logfile = /tmp/supervisord.log
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:cat]
    command=/bin/cat
    
    venv27$ bin/supervisord -n -c supervisord.conf 
    2015-08-11 10:23:19,885 INFO Increased RLIMIT_NOFILE limit to 1024
    2015-08-11 10:23:19,897 INFO RPC interface 'supervisor' initialized
    2015-08-11 10:23:19,898 CRIT Server 'inet_http_server' running without any HTTP authentication checking
    2015-08-11 10:23:19,898 INFO supervisord started with pid 33221
    2015-08-11 10:23:20,903 INFO spawned: 'cat' with pid 33224
    2015-08-11 10:23:21,909 INFO success: cat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    ^C2015-08-11 10:23:32,799 WARN received SIGINT indicating exit request
    2015-08-11 10:23:32,799 INFO waiting for cat to die
    2015-08-11 10:23:32,800 INFO stopped: cat (terminated by SIGTERM)
    
    venv27$ bin/python
    Python 2.7.10 (default, Jul 13 2015, 12:05:58) 
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from supervisor import events
    >>> events.ProcessGroupAddedEvent
    <class supervisor.events.ProcessGroupAddedEvent at 0x106dffa10>

**Comment by josemanimala** [comment]
thanks @mnaberez. I will check my build steps again and try to figure out what went wrong.

**Comment by riyadparvez** [comment]
I still see the same error on supervisord 3.3.0.

**Comment by qinguanri** [comment]
@mnaberez, I can also see the same error on supervisord 3.3.1. I can install supervisord and reload successfully. But when I reboot my server, I find that supervisord can not autorestart. So I start it by hand. Then I got the error.  Now I don't know how to resolve it.

```
root@kylin-os:/usr/local/lib/python2.7/dist-packages/supervisor# supervisord -v
3.3.1
root@kylin-os:/usr/local/lib/python2.7/dist-packages/supervisor# supervisord -c /etc/supervisor/supervisord.conf
2016-11-29 21:24:39,720 CRIT Supervisor running as root (no user in config file)
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 365, in main
    go(options)
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 375, in go
    d.main()
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 84, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 92, in run
    self.add_process_group(config)
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 126, in add_process_group
    events.notify(events.ProcessGroupAddedEvent(name))
AttributeError: 'module' object has no attribute 'ProcessGroupAddedEvent'
```

**Comment by npchp110** [comment]
@qinguanri try this:
1, apt-get remove supervisor
maybe you install an old version of supervisor via apt-get
apt-get will install supervisor at /usr/lib/python2.7/dist-packages/supervisor
pip will install supervisor at /usr/local/lib/python2.7/dist-packages/supervisor
