### ISSUE TITLE
filedescriptor out of range in select()

### ISSUE THREAD

**Issue by Ange7** [Supervisor/supervisor#739]
I'm using supervisor v3.2.3 on Ubuntu Server 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)

> supervisord -v 
> 3.2.3

If i configure more than 200 process in configuration(s) file(s) of supervisor i have this error : 

> Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.2.3', 'console_scripts', 'supervisord')()
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 367, in main
    go(options)
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 377, in go
    d.main()
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 83, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 100, in run
    self.runforever()
  File "/usr/local/lib/python2.7/dist-packages/supervisor/supervisord.py", line 220, in runforever
    r, w, x = self.options.select(r, w, x, timeout)
  File "/usr/local/lib/python2.7/dist-packages/supervisor/options.py", line 1227, in select
    return select.select(r, w, x, timeout)
ValueError: filedescriptor out of range in select()

thank you

**Comment by mnaberez** [comment]
Fixed in 9e6aa44 (PR #129).

Note from [changelog](https://github.com/Supervisor/supervisor/blob/3e541a34a4ab741e67ff4406eb2727599903c6e3/CHANGES.txt#L27-L33):

> - ``supervisord`` will now use ``kqueue``, ``poll``, or ``select`` to monitor
>   its file descriptors, in that order, depending on what is available on the
>   system.  Previous versions used ``select`` only and would crash with the error
>   ``ValueError: filedescriptor out of range in select()`` when running a large
>   number of subprocesses (whatever number resulted in enough file descriptors
>   to exceed the fixed-size file descriptor table used by ``select``, which is
>   typically 1024).  Patch by Igor Sobreira.

This change will be released in Supervisor 3.3.0.
