### ISSUE TITLE
Interrupted system call @ startup

### ISSUE THREAD

**Issue by larrypl** [Supervisor/supervisor#817]
Got the following while starting up, and something similar when supervisorctl update is run. Seems like it _might_ be related to this job definition; specifically, the /bin/bash version on the command line is too old to recognize “|&”:
```
[program:<elided>]
command = /bin/bash -c '[[ $(hostname -s) =~ (<elided>) ]] || exit 4; set -o pipefail; <elided> -C <elided> -O <elided> -S 161-50.<elided> 1001 |& <elided>/bin/rotatelogs <elided>/$(hostname -s)-%(program_name)s_%(process_num)02d_%%Y-%%m-%%d.log 86400'
process_name = %(program_name)s_%(process_num)02d
user = <elided>
directory = /
stopsignal = INT
stopasgroup = true
killasgroup = true
numprocs = 1
startsecs = 0
exitcodes = 1, 4
autorestart = unexpected
environment = API_ROOT="<elided>",CONFIG_ROOT="<elided>",CONFIG_FILE="local_config_queue.php",MODEL_ROOT="<elided>/model",LOCALE_ROOT="<elided>/l10n",TZ="UTC",BASE_DIR="<elided>",BOOTSTRAP_FILE="Bootstrap.php"
redirect_stderr = true
stdout_logfile=/tmp/supervisortest/%(program_name)s.%(process_num)02d.out
stdout_logfile_maxbytes=1024MB
stdout_logfile_backups=9999
```
---
```
2016-08-31 10:48:02,812 INFO spawned: '<elided>    load_entry_point('supervisor==3.3.1', 'console_scripts', 'supervisord')()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/supervisord.py", line 365, in main
    go(options)
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/supervisord.py", line 375, in go
    d.main()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/supervisord.py", line 84, in main
    self.run()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/supervisord.py", line 101, in run
    self.runforever()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/supervisord.py", line 253, in runforever
    group.transition()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/process.py", line 761, in transition
    proc.transition()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/process.py", line 605, in transition
    self.spawn()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/process.py", line 252, in spawn
    return self._spawn_as_parent(pid)
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/process.py", line 262, in _spawn_as_parent
    options.logger.info('spawned: %r with pid %s' % (self.config.name, pid))
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/loggers.py", line 275, in info
    self.log(LevelsByName.INFO, msg, **kw)
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/loggers.py", line 293, in log
    handler.emit(record)
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/loggers.py", line 86, in emit
    self.handleError()
  File "/Users/larry/lib/python2.7/site-packages/supervisor-3.3.1-py2.7.egg/supervisor/loggers.py", line 90, in handleError
    traceback.print_exception(ei[0], ei[1], ei[2], None, sys.stderr)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
IOError: [Errno 4] Interrupted system call
```
---
Obviously anything on the command line should not crash supervisord, nor prevent it from starting up.

**Comment by mnaberez** [comment]
Are you able to provide an config example that we can run to reproduce it?  I haven't seen this before and with all the `<elided> <elided>` stuff I'd just have to guess at what might cause it.  A runnable example would help a lot.

**Comment by mnaberez** [comment]
Possibly related: #461.  We'd need to know the operating system and full config file to know if it's related to that one or not.

**Comment by larrypl** [comment]
Let me see if I can reproduce it with a smaller example, with nothing elided.

**Comment by larrypl** [comment]
Oops, hit the wrong button; hence the close and reopen.

**Comment by larrypl** [comment]
Here's a configuration that fails, with comments stripped out for brevity:
```
[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)
[supervisord]
logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10           ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=false               ; (start in foreground if true;default false)
minfds=4096
minprocs=4096
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket
[program:cattest]
command=/opt/local/bin/gcat
[program:gdate]
command=bash -c 'while /opt/local/bin/gdate +%%Y%%m%%d%%H%%M%%S.%%N; do sleep $((7 + RANDOM %% 4 + RANDOM %% 4)); done'
numprocs=10
process_name=%(program_name)s_%(process_num)02d
[include]
files = supervisord.d/*.ini, /tmp/4mb
larryp-mbp:~ root# cat ~larry/etc/supervisord.d/*.ini
[program:jobserver]
command = /opt/local/bin/gcat -nvet
[program:sleep2]
command = bash -cx 'sleepytime=$((81 + RANDOM %% 20 + RANDOM %% 20)); echo $sleepytime; sleep $sleepytime'
autorestart = true
larryp-mbp:~ root# cat /tmp/4mb
;=========================================================================================================================================================================================================
[program:testcrash]
command = /bin/bash -c 'date |& wc'
process_name = %(program_name)s_%(process_num)02d
directory = /
stopsignal = INT
stopasgroup = true
killasgroup = true
numprocs = 15
startsecs = 0
exitcodes = 1, 4
autorestart = unexpected
redirect_stderr = true
stdout_logfile=/tmp/supervisortest/%(program_name)s.%(process_num)02d.out
stdout_logfile_maxbytes=1024MB
stdout_logfile_backups=9999
```
This is being tested on MacOS 10.11.6, for deployment to CentOS 6.7 systems.

Thanks for the quick response, BTW!

**Comment by larrypl** [comment]
Well it's not the ampersand.

It seems to be caused by some interaction between numprocs and startsecs. When startsecs is set to 0 and numprocs is set to 4, Supervisord continues, but with numprocs = 5 it fails. Then when startsecs defaults to 1 numprocs = 5 succeeds but numprocs = 6 fails.
