### ISSUE TITLE
Supervisor xmlrpc crash after starting large numer or processes

### ISSUE THREAD

**Issue by tiborb** [Supervisor/supervisor#852]
I have a config file containing ~200 processes.

``supervisorctl start all`` will start normally and after about two minutes it exits with ``error: <class 'xmlrpclib.ProtocolError'>, <ProtocolError for 127.0.0.1/RPC2: 500 Internal Server Error>: file: /usr/lib/python2.7/dist-packages/supervisor/xmlrpc.py line: 470
`` and leaving configured processes stopped.

The supervisor service itself is running, but no xmlrpc calls are possible making supervisorctl useless.

When the config file contains less configured processes the problem does not occur.

Any ideas?

Env: Ubuntu

**Comment by ZyanKLee** [comment]
some more information on this matter:

after we raised the open files limit (ulimit -n 65535) and ran the supervisord in foreground we got some meaningful (?) error message:

```
2016-11-16 16:25:03,045 INFO spawned: 'test-process' with pid 14720
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.0b2', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 360, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 370, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 83, in main
    self.run()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 100, in run
    self.runforever()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 218, in runforever
    r, w, x = self.options.select(r, w, x, timeout)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1156, in select
    return select.select(r, w, x, timeout)
ValueError: filedescriptor out of range in select()
```

**Comment by mnaberez** [comment]
> `ValueError: filedescriptor out of range in select()`

This [was fixed](https://github.com/Supervisor/supervisor/blob/3.3.0/CHANGES.txt#L7) in Supervisor 3.3.0.  Please upgrade to a new version.
