### ISSUE TITLE
Bad command causes supervisorctl to crash

### ISSUE THREAD

**Issue by mnaberez** [Supervisor/supervisor#913]
Issuing a bad `supervisorctl` command on Supervisor 3.3.1 shows the expected error message:
```
$ supervisord --version
3.3.1
$ supervisorctl badcmd
*** Unknown syntax: badcmd
$
```

Issuing a bad `supervisorctl` command on master (bb0332fc36e2001066bac528a68eda55f5914fbc) crashes:
```
$ supervisord --version
4.0.0.dev0
$ supervisorctl badcmd
Traceback (most recent call last):
  File "/usr/local/bin/supervisorctl", line 11, in <module>
    load_entry_point('supervisor', 'console_scripts', 'supervisorctl')()
  File "/path/to/supervisorctl.py", line 1360, in main
    c.onecmd(" ".join(options.args))
  File "/path/to/supervisorctl.py", line 202, in onecmd
    result = self.onecmd_run(line)
  File "/path/to/supervisorctl.py", line 227, in onecmd_run
    return self.default(line)
  File "/path/to/supervisorctl.py", line 141, in default
    super(Controller, self).default(line)
TypeError: super() argument 1 must be type, not classobj
$
```

Possibly related to the changes merged in #668.

**Comment by hhsue** [comment]
https://github.com/hhsue/supervisor/commit/3090266c5787911506afe0a3e8799771221f34f7
an idea, but not sure if it's good. 

```
$ supervisorctl asdf
*** Unknown syntax: asdf
```
