### ISSUE TITLE
Can not start supervisord

### ISSUE THREAD

**Issue by baiyuxiong** [Supervisor/supervisor#931]
# supervisord 
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'supervisor==3.1.3' distribution was not found and is required by the application

Re-install, no error :
# pip install supervisor
Collecting supervisor
Requirement already satisfied: meld3>=0.6.5 in /usr/local/lib/python2.7/site-packages (from supervisor)
Installing collected packages: supervisor
Successfully installed supervisor-3.3.1

# python -V
Python 2.7.13

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
